### ISSUE TITLE
Deprecation notice with Symfony 4.2

### ISSUE THREAD

**Issue by cs278** [mariusbalcytis/gentle-force-bundle#15]
Deprecation notice is being raised from `src/DependencyInjection/Configuration.php:15`:

> A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

**Comment by Imagica** [comment]
Same issue found here:
https://github.com/symfony/monolog-bundle/pull/281/files/45742f1a97291edd1401ecb58024488bbd793038

**Comment by maxhelias** [comment]
Fixed by #17
