### ISSUE TITLE
How to easily disable bundle in dev mode?

### ISSUE THREAD

**Issue by kirrg001** [mariusbalcytis/gentle-force-bundle#27]
Hi there!

Thanks for the bundle. Working great!

I was wondering how to disable the bundle in dev mode easily.
Goal is to easily switch it on/off in dev mode.

I was looking for a `enabled: true | false` parameter/configuration.

Thanks!

**Comment by mariusbalcytis** [comment]
You should just enable the bundle only for `prod` environment, not all of them. If you're using 3.x structure, configuration should be also moved to `config_prod.yml`.

Please give feedback if this solves your problem.

**Comment by mariusbalcytis** [comment]
I see now that I probably misunderstood your use-case. You want to still easily enable or disable it with some env variable or similar approach, right?

**Comment by kirrg001** [comment]
Hi! Thanks for quick reply.

e.g.

A general rate limiting config for all envs (staging, production)
maba_gentle_force.yml
   redis:...
   limits: ....

Dev env is disabled. And can be enabled easily.

dev/maba_gentle_force.yml
   enabled: false

If I create a prod/maba_gentle_force.yml, I don't see a way to easily enable dev? Copying the whole prod config is not comfortable :)

I really don't mind if I can enable rate limiting locally via an env variable. That would be cool too!

I hope it's clear :)
Thank you!

**Comment by kirrg001** [comment]
I have solved it by adding

**config/packages/maba_gentle_force.yml**: with redis and listeners config for all envs.
**config/packages/dev/maba_gentle_force.yml:** limits for dev env (high limits)
**config/packages/prod/maba_gentle_force.yml:** limits for prod env (normal limits)

It's not super comfortable, but this gives me the ability to easily change the dev limits and test rate limiting locally.

Furthermore I have deactivated test env completely by defining in bundles.php

```
Maba\Bundle\GentleForceBundle\MabaGentleForceBundle::class              => ['dev' => true, 'prod' => true],
```
