### ISSUE TITLE
Doesn't work for login brute force protection

### ISSUE THREAD

**Issue by tplantta** [mariusbalcytis/gentle-force-bundle#3]
I installed this to use for login brute force protection in a Symfony 3.4 project and found it didn't work at all for that use case. That is because onRequest in the listener registered by this bundle is never called on failed logins, as it has lower priority than FirewallListener performing the authentication.

I tried changing the priority from 1 to 9 in RequestListener::getSubscribedEvents() and got it working as expected. That is not a proper fix though, as in other use cases the listener being called after authentication is correct (and required) behaviour.

So what is needed is a way to register the listeners with different priority depending on what it is to be used for.

**Comment by mariusbalcytis** [comment]
As I understand, to be called after FirewallListener is needed only when user-related identifier is used for bruteforce attempt counting, like username. Or do you see any other use-case?

What I'm thinking about is to relate this with identifiers used. If it can be resolved before FirewallListener (like IP), it should run as soon as it can.

**Comment by tplantta** [comment]
It is not just a matter of identifier used , but also of what is being limited. Limiting authentication failures, essentially limiting access to the FirewallListener is different from rate-limiting valid requests to the actual application code behind that firewall. 

1. When limiting authentication failures with any identifier, user based or not, it must run before FirewallListener, because the that is what we are limiting access to. The event does not propagate beyond FirewallListener on authentication failure anyway. 

2. When rate-limiting valid requests per user it must act on authenticated user identity and thus must run after FirewallListener, even if the identifier could be resolved earlier.

3. When rate-limiting requests based on ip address, or some other identifier not related to user identity there is no hard requirement to run before or after FirewallListener, but as early as possible is preferable for performance reasons.

**Comment by mariusbalcytis** [comment]
Each identifier provider can have priority assigned and run after FirewallListener. The default is to run before that (with priority `1000`).

This fixes the issue with not being able to limit authentication failures when authenticating with FirewallListener.

To note some details on your written use-cases:

1. If limiting authentication failures with any identifier which could be provided before authentication ( (IP etc), it will work as expected. Limiting authentication failures by username is (and was not) supported out-of-the-box with listener configurations, as username is provided from the token, which is not set until authentication is passed.

2. If rate-limiting by user, it will run after FirewallListener, as no user would be got before that.

3. If rate-limiting by any other identifier, it will run with priority 1000, which is before any other default listener in symfony. This will allow to rate-limit authentication failures.

Please comment if it does not yet suit your needs.
