### ISSUE TITLE
Add a "whitelist" of IP

### ISSUE THREAD

**Issue by nathanael-anstett** [mariusbalcytis/gentle-force-bundle#32]
Hello, is it possible to define a whitelist of IP ?

I want to add an anti brute force feature on my Symfony API. Let's say I don't want regular users to be able to make more than 100 requests per hour, but I want my IP to be able to do more than 100 requests per hour. Is it possible ?

**Comment by mariusbalcytis** [comment]
Not directly in the configuration, but you can implement a new `IdentifierProviderInterface` (and tag it, and use the new identifier in the configuration) which would return `null` on whitelisted IPs, and the real IP otherwise.

**Comment by nathanael-anstett** [comment]
Hello, thank you very much for your quick answer, it perfectly answers my question. Thank you for your work 🔥
