### ISSUE TITLE
redis dsn connection method ?

### ISSUE THREAD

**Issue by ibasaw** [mariusbalcytis/gentle-force-bundle#35]
hi,

How to conect to redis with DSN instance ?

like this

`redis[s]://[pass@][ip|host|socket[:port]][/db-index]
`

as mentioned here : https://symfony.com/doc/current/components/cache/adapters/redis_adapter.html

**Comment by mariusbalcytis** [comment]
Please see [redis configuration](https://github.com/mariusbalcytis/gentle-force-bundle#redis) section in the readme.

See [predis docs](https://github.com/predis/predis) for configuration reference if needed.

**Comment by ibasaw** [comment]
already did before i post the issue. i know how to configure redis, this is only with this bundle the issue. only want to pass the db-index
